
version: 2.1

jobs:
  build-and-deploy-staging:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - run: composer install
      - run: composer dump-autoload
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "a7:82:56:b6:47:bd:44:45:98:83:35:2f:1f:c9:c1:16"
      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt update
      - run: sudo apt-get install rsync
      - run:
          rsync -avzr --rsh="ssh -p $SSH_PORT" --rsync-path=/usr/bin/rsync --delete --exclude .gitattributes --exclude .gitignore --exclude phpcs.xml.dist --exclude /.circleci/ --exclude /.git/ --exclude /node_modules/ ./ $SSH_USER@$SSH_HOST:/home/heyton/staging.heytony.ca/wp-content/themes/avada-child
  build-and-deploy-production:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - run: composer install
      - run: composer dump-autoload
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "a7:82:56:b6:47:bd:44:45:98:83:35:2f:1f:c9:c1:16"
      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt update
      - run: sudo apt-get install rsync
      - run:
          rsync -avzr --delete --exclude .gitattributes --exclude .gitignore --exclude phpcs.xml.dist --exclude /.circleci/ --exclude /.git/ --exclude /node_modules/ --rsh="ssh -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/home/heyton/public_html/wp-content/themes/avada-child

workflows:
  version: 2.1
  build_and_deploy_staging:
    jobs:
      - build-and-deploy-staging:
          filters:
            branches:
              only: staging
  build_and_deploy_production:
    jobs:
      - build-and-deploy-production:
          filters:
            branches:
              only: main
