
version: 2.1

jobs:
  build-and-deploy-staging:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "7c:2f:62:ca:77:bd:63:73:8a:b9:c3:63:a5:8c:9e:e6"
      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt install rsync
      - run:
          rsync -avzr --delete --exclude .gitattributes --exclude .gitignore --exclude /.circleci/ --exclude /.git/ --exclude /node_modules/ --rsh="ssh -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/home/heyton/staging.heytony.ca/wp-content/themes/avada-child
  build-and-deploy-production:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "7c:2f:62:ca:77:bd:63:73:8a:b9:c3:63:a5:8c:9e:e6"
      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt install rsync
      - run:
          rsync -avzr --delete --exclude .gitattributes --exclude .gitignore --exclude /.circleci/ --exclude /.git/ --exclude /node_modules/ --rsh="ssh -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/home/heyton/staging.heytony.ca/wp-content/themes/avada-child

workflows:
  version: 2.1
  build_and_deploy_staging:
    jobs:
      - build-and-deploy-staging:
          filters:
            branches:
              only: staging
  build_and_deploy_production:
    jobs:
      - build-and-deploy-production:
          filters:
            branches:
              only: main
