
version: 2.1

jobs:
  build-and-deploy-staging:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - run: composer install
      - run: composer dump-autoload
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "8a:5d:d4:92:c5:72:13:3b:c4:e8:29:12:85:30:8a:d6"
      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt update
      - run: sudo apt install rsync
      - run:
          rsync -avzr --delete --delete-excluded --exclude-from='exclude-list.txt' -e "ssh -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/home/heyton/staging.heytony.ca/wp-content/themes/avada-child

  build-and-deploy-production:
    docker:
      - image: cimg/php:7.4-node
    steps:
      - checkout
      - run: composer install
      - run: composer dump-autoload
      - run: npm install
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "8a:5d:d4:92:c5:72:13:3b:c4:e8:29:12:85:30:8a:d6"
      - run: ssh-keyscan -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts
      - run: sudo apt update
      - run: sudo apt install rsync
      - run:
          rsync -avzr --delete --delete-excluded --exclude-from='exclude-list.txt' -e "ssh -p $SSH_PORT" ./ $SSH_USER@$SSH_HOST:/home/heyton/public_html/wp-content/themes/avada-child

workflows:
  version: 2.1
  build_and_deploy_staging:
    jobs:
      - build-and-deploy-staging:
          filters:
            branches:
              only: staging
  build_and_deploy_production:
    jobs:
      - build-and-deploy-production:
          filters:
            branches:
              only: main
